# This is a basic workflow to help you get started with Actions

name: Library Book Scheduler

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # at midnight every day, to configure: https://crontab.guru/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: setup-python
        name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - id: install
        name: Install python packages
        run: pip install -r requirements.txt

      - id: executeBooksETL
        name: Execute books ETL
        run: jupyter execute etl_books.ipynb

      - id: executeBorrowersETL
        name: Execute borrowers ETL
        run: jupyter execute etl_borrowers.ipynb

      - id: executeDatesCheckoutsETL
        name: Execute Dates & Checkouts ETL
        run: jupyter execute etl_checkouts.ipynb
